# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Teknobyen' do
pod 'Firebase', '>= 2.5.1'
pod 'Fuzi', '~> 0.3.0'
pod 'PIDatePicker', '~> 0.1.0'
pod 'UIColor_Hex_Swift', '~> 2.1'
pod 'Locksmith', '~> 2.0.8'
pod 'EPCalendarPicker'

end
